package cn.edu.sjzc.teacher.util;

import cn.edu.sjzc.teacher.uiActivity.AdvStudentInfoActivity;
import cn.edu.sjzc.teacher.uiActivity.AppStartActivicy;
import cn.edu.sjzc.teacher.uiActivity.BaseActivity;
import cn.edu.sjzc.teacher.uiActivity.CourseActivity;
import cn.edu.sjzc.teacher.uiActivity.FindTeacherActivity;
import cn.edu.sjzc.teacher.uiActivity.GuideActivity;
import cn.edu.sjzc.teacher.uiActivity.HomeExchangeActivity;
import cn.edu.sjzc.teacher.uiActivity.HomeInfoActivity;
import cn.edu.sjzc.teacher.uiActivity.HomeNewsActivity;
import cn.edu.sjzc.teacher.uiActivity.LoginActivity;
import cn.edu.sjzc.teacher.uiActivity.LoginDemoActivity;
import cn.edu.sjzc.teacher.uiActivity.MyRankingActivity;
import cn.edu.sjzc.teacher.uiActivity.MyRankingInfoActivity;
import cn.edu.sjzc.teacher.uiActivity.PerChangeInfoActivity;
import cn.edu.sjzc.teacher.uiActivity.PerChangePasswordActivity;
import cn.edu.sjzc.teacher.uiActivity.PerPersonalInfoActivity;
import cn.edu.sjzc.teacher.uiActivity.PerScheduleActivity;
import cn.edu.sjzc.teacher.uiActivity.SignActivity;
import cn.edu.sjzc.teacher.uiActivity.TeacherRankingActivity;
import cn.edu.sjzc.teacher.uiActivity.TeacherRankingInfoActivity;
import cn.edu.sjzc.teacher.uiFragment.BaseFragment;
import cn.edu.sjzc.teacher.uiFragment.FindAdviceFragment;
import cn.edu.sjzc.teacher.uiFragment.FindEvaluationFragment;
import cn.edu.sjzc.teacher.uiFragment.FindStudentFragment;
import cn.edu.sjzc.teacher.uiFragment.HomePageFragment;
import cn.edu.sjzc.teacher.uiFragment.MainTabActivity;
import cn.edu.sjzc.teacher.uiFragment.PersonalCenterFragment;

public class ValueUtil {
	public static AppStartActivicy appStartActivicy;
	public static GuideActivity guideActivity;
	public static HomeExchangeActivity homeExchangeActivity;
	public static HomeInfoActivity homeInfoActivity;
	public static HomeNewsActivity homeNewsActivity;
	public static LoginActivity loginActivity;
	public static PerChangeInfoActivity perChangeInfoActivity;
	public static PerChangePasswordActivity perChangePasswordActivity;
	public static PerPersonalInfoActivity perPersonalInfoActivity;
	public static PerScheduleActivity perScheduleActivity;
	public static BaseActivity baseActivity;
	public static LoginDemoActivity loginDemoActivity;
    public static MainTabActivity mainTabActivity;
    public static AdvStudentInfoActivity advStudentInfoActivity;
    public static CourseActivity courseActivity;
    public static FindTeacherActivity findTeacherActivity;
    public static MyRankingActivity myRankingActivity;
    public static MyRankingInfoActivity myRankingInfoActivity;
    public static SignActivity signActivity;
    public static TeacherRankingActivity teacherRankingActivity;
    public static TeacherRankingInfoActivity teacherRankingInfoActivity;
    public static BaseFragment baseFragment;
    public static FindAdviceFragment findAdviceFragment;
    public static FindEvaluationFragment findEvaluationFragment;
    public static FindStudentFragment findStudentFragment;
    public static HomePageFragment homePageFragment;
    public static PersonalCenterFragment personalCenterFragment;

}
